"""Token

Revision ID: 3ed19a5c77d6
Revises: 8d4bf195fb16
Create Date: 2019-12-20 23:18:45.742720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ed19a5c77d6'
down_revision = '8d4bf195fb16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_messages_read_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_messages_read_time', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
