"""Token

Revision ID: 8d4bf195fb16
Revises: fe1b2edd5cfb
Create Date: 2019-12-20 23:05:24.762769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d4bf195fb16'
down_revision = 'fe1b2edd5cfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_messages_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_messages_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
