"""message count

Revision ID: bbd75c3c80df
Revises: 970d4d075805
Create Date: 2019-12-20 13:48:19.979709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbd75c3c80df'
down_revision = '970d4d075805'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_message_read_time', sa.DateTime(), nullable=True))
    op.drop_column('user', 'last_messages_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_messages_read_time', sa.DATETIME(), nullable=True))
    op.drop_column('user', 'last_message_read_time')
    # ### end Alembic commands ###
