"""Token

Revision ID: fe1b2edd5cfb
Revises: bbd75c3c80df
Create Date: 2019-12-20 23:04:44.697004

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe1b2edd5cfb'
down_revision = 'bbd75c3c80df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_messages_read_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_messages_read_time', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
